Feature/locales on clientapp
vlbondarenko/mylife.org pull request #8
Opened 2022-08-12 07:56 UTC by vlbondarenko

2022-08-12 10:42 UTC, AkulovOleg requested changes

2022-08-12 10:42 UTC, AkulovOleg commented on clientapp/src/components/home/Header.vue
> +      setLocale(locale).then( () => { router.go(0) });
зачем мы всё таки делаем тут router.go(0)?

2022-08-12 10:42 UTC, AkulovOleg commented on serverapp/src/Application/Resources/UseCases/UserProfiles/Queries/GetUserProfileQueryHandler.ru.resx
> +﻿<?xml version="1.0" encoding="utf-8"?>
Судя по названию ты сделал словарь для Handler, но тогда их будет миллион, смысла в этом вообще нет. Т.к. проект оч маленький тут можно сделать 1 общий словарь для ошибок

2022-08-12 10:42 UTC, AkulovOleg commented on serverapp/src/Application/UseCases/UserProfiles/Queries/GetUserProfileQuery.cs
> +using Application.Exceptions;
не используется вроде

2022-08-12 10:42 UTC, AkulovOleg commented on serverapp/src/WebApi/Controllers/ApiControllerBase.cs
> +                Expires = DateTime.UtcNow.AddHours(4),
А в чём смысл ставить ExpirationDate?

2022-08-12 10:42 UTC, AkulovOleg commented on serverapp/src/WebApi/appsettings.Development.json
> +  "TokenKey": "94d7e2b61061af050b21391c665910fc5443b735"
Подскажи что за токен тут?

2022-08-12 10:42 UTC, AkulovOleg commented on serverapp/src/WebApi/Controllers/LocalizationController.cs
> +        public async Task<IActionResult> ChangeLanguageKey([FromBody] string locale)
как думаешь может есть смысл /api/Localization/change/{lang}?

2022-08-12 10:42 UTC, AkulovOleg commented on serverapp/tests/Application.Tests/Common/ApplicationHandlerTestsBase.cs
>          protected readonly ApplicationDbContext _applicationDbContext;
Что-то я не понял как так в тестах идёт не Mock контекста

2022-08-12 10:42 UTC, AkulovOleg commented on serverapp/src/WebApi/Startup.cs
> +            var supportedCultures = new CultureInfo[]
Может вытащим в readonly список приватный в классе

2022-08-12 10:42 UTC, AkulovOleg commented on serverapp/src/WebApi/Startup.cs
> +                DefaultRequestCulture = new RequestCulture(new CultureInfo("ru")),
А тут предлагаю по умолч брать [0] элемент из списка того)

2022-08-12 10:42 UTC, AkulovOleg commented on serverapp/src/Application/UseCases/UserProfiles/Queries/GetUserProfileQuery.cs
> +            var localizedError = _localizer["userNotFound", query.Id];
Это же используется только внутри if который ниже, есть смысл передвинуть его внутрь

2022-08-12 10:42 UTC, AkulovOleg commented on clientapp/src/services/authService.ts
> +        return axios.post(API_URL + 'User/forgotpassword', { email: userEmail })
У тебя вроде контроллеры не поменялись, а тут url ты поменял

2022-08-12 10:42 UTC, AkulovOleg commented on clientapp/src/helpers/localizer.ts
> +  let regexp = new RegExp('(?<=c=)[a-zA-Z,-]+')
Меня немного напрягает такой формат записи в куке, может есть смысл на бэке поменять чтобы он парсил что-то другое? Например просто ru или en

2022-08-12 10:42 UTC, AkulovOleg commented on serverapp/src/WebApi/Program.cs
> +            await serviceScope.ServiceProvider.GetService<ApplicationDbContext>()!.Database.MigrateAsync();
Я бы делал отдельный Extension тут. Ну и в таком контексте лучше GetRequiredService использовать

2022-08-12 10:52 UTC, vlbondarenko commented on clientapp/src/components/home/Header.vue
> +      setLocale(locale).then( () => { router.go(0) });
это перезагрузка текущей страницы. 0 - это порядковый номер страницы в истории, т е тут просто текущая страница перезагружается

2022-08-12 10:57 UTC, vlbondarenko commented on serverapp/src/Application/Resources/UseCases/UserProfiles/Queries/GetUserProfileQueryHandler.ru.resx
> +﻿<?xml version="1.0" encoding="utf-8"?>
Так в документации написано) В этом то и прикол, что локали подтягиваются по названию типа) Если честно, примеров с общими словарями не встречал. Да и при настройке локализации указывается только корневая папка с файлами ресурсов, а дальше уже автоматом идет сопоставление по именам.

2022-08-12 10:57 UTC, vlbondarenko commented on serverapp/src/Application/Resources/UseCases/UserProfiles/Queries/GetUserProfileQueryHandler.ru.resx
> +﻿<?xml version="1.0" encoding="utf-8"?>
Попробую еще накопать что нибудь по общим словарям

2022-08-12 10:58 UTC, vlbondarenko commented on serverapp/src/Application/UseCases/UserProfiles/Queries/GetUserProfileQuery.cs
> +using Application.Exceptions;
Там лежит NotFoundException, который юзается в хендлере

2022-08-12 10:58 UTC, vlbondarenko commented on serverapp/src/WebApi/Controllers/ApiControllerBase.cs
> +                Expires = DateTime.UtcNow.AddHours(4),
Не знаю, это легаси 🙂 Уберу

2022-08-12 11:02 UTC, vlbondarenko commented on serverapp/src/WebApi/appsettings.Development.json
> +  "TokenKey": "94d7e2b61061af050b21391c665910fc5443b735"
У меня же своя авторизация, этот токен нужен для симметричного ключа безопасности, для sha512 алгоритма при создании jwt токена

2022-08-12 11:06 UTC, vlbondarenko commented on serverapp/src/Application/UseCases/UserProfiles/Queries/GetUserProfileQuery.cs
> +            var localizedError = _localizer["userNotFound", query.Id];
Это только для дебаггинга) забыл исправить. так мне приходилось каждый раз в режиме отладки исправлять айдишник, чтобы код попадал в тело конструкции if. Потом вот это добавил, чтобы проверять работоспособность локализатора. Хотя можно было бы просто воспользоваться Add Watch, но я не ищу легких путей 🙂

2022-08-12 11:07 UTC, vlbondarenko commented on clientapp/src/services/authService.ts
> +        return axios.post(API_URL + 'User/forgotpassword', { email: userEmail })
Я сам в ахуе был, когда увидел, что у меня нет контроллера account 🙂 хз как так получилось. Поэтому исправил тут)

2022-08-12 11:13 UTC, vlbondarenko commented on serverapp/src/Application/UseCases/UserProfiles/Queries/GetUserProfileQuery.cs
> +            var localizedError = _localizer["userNotFound", query.Id];
Поправил

2022-08-12 11:15 UTC, vlbondarenko commented on serverapp/src/WebApi/Controllers/ApiControllerBase.cs
> +                Expires = DateTime.UtcNow.AddHours(4),
Хотя не, вспомнил - это нужно для метода подтверждения email. Задумка была такой - типа при переходе по сслыке в куки добавлялся токен, который нужен на бэке для подтверждения адреса. И срок действия этого токена ограничен, в данном случае равен 4 часам

2022-08-12 11:32 UTC, vlbondarenko commented on serverapp/src/WebApi/Startup.cs
> +                DefaultRequestCulture = new RequestCulture(new CultureInfo("ru")),
поправил

2022-08-12 11:33 UTC, vlbondarenko commented on serverapp/src/WebApi/Program.cs
> +            await serviceScope.ServiceProvider.GetService<ApplicationDbContext>()!.Database.MigrateAsync();
сделал extension метод

2022-08-12 12:17 UTC, vlbondarenko commented on clientapp/src/helpers/localizer.ts
> +  let regexp = new RegExp('(?<=c=)[a-zA-Z,-]+')
Замутил кастомный cookie provider. Теперь в куках просто en/ru

2022-08-12 14:38 UTC, AkulovOleg commented on clientapp/src/components/home/Header.vue
> +      setLocale(locale).then( () => { router.go(0) });
Это я понял, а зачем?))

2022-08-12 14:41 UTC, AkulovOleg commented on serverapp/src/WebApi/Controllers/ApiControllerBase.cs
> +                Expires = DateTime.UtcNow.AddHours(4),
Вообще не помнимаю какой смысл этого метода. У тебя под кажду куку должны быть свои настройки, зачем тут объединять их все? В такой концепции у тебя и языковая кука будет 4ч жить.

Вообще мне не оч понятен смысл ApiControllerBase класса этого

2022-08-15 09:35 UTC, AkulovOleg commented on serverapp/src/WebApi/Controllers/ApiControllerBase.cs
> +            Response.Cookies.Append(key, value, options);
Всё равно не понимаю целесообзраность этого метода. Почему везде не писать Response.Cookies.Append где надо?

2022-08-15 09:38 UTC, AkulovOleg commented on clientapp/src/main.ts
> +    locale: 'ru',
Слушай, у тебя тут вроде получается на бэке по умолч en, а здесь ru

2022-08-21 06:48 UTC, vlbondarenko commented on serverapp/src/WebApi/Controllers/ApiControllerBase.cs
> +                Expires = DateTime.UtcNow.AddHours(4),
убрал ApiControllerBase

2022-08-21 06:49 UTC, vlbondarenko commented on serverapp/src/WebApi/Controllers/ApiControllerBase.cs
> +            Response.Cookies.Append(key, value, options);
Убрал. Сделал Cookies.Append  где надо

2022-08-21 06:49 UTC, vlbondarenko commented on clientapp/src/main.ts
> +    locale: 'ru',
Поправил

2022-08-21 19:41 UTC, vlbondarenko commented on clientapp/src/components/home/Header.vue
> +      setLocale(locale).then( () => { router.go(0) });
я еблан 🙂 я после обновления кук не устанавливал новую локаль для i18n. Прописал в then установку новой локали

2022-08-23 15:42 UTC, AkulovOleg requested changes

2022-08-23 15:42 UTC, AkulovOleg commented on serverapp/src/WebApi/Controllers/LocalizationController.cs
> +                Expires = DateTime.UtcNow.AddHours(4),
Всё по прежнему не понимаю почему 4ч для языка)) Это угар))

2022-08-23 15:42 UTC, AkulovOleg commented on serverapp/src/WebApi/Controllers/UserController.cs
> +                    Expires = DateTime.UtcNow.AddHours(4)
Поч ты решил везде время задать я не понимаю))

2022-08-23 15:42 UTC, AkulovOleg commented on serverapp/src/WebApi/Controllers/UserController.cs
> +            var userId = Request.Cookies["userId"];
Бесполезные локальные переменные) понимаю что к задаче не относится, но в глаза бросается

2022-08-25 06:59 UTC, vlbondarenko commented on serverapp/src/WebApi/Controllers/LocalizationController.cs
> +        public async Task<IActionResult> ChangeLanguageKey([FromBody] string locale)
change в урле я бы не указывал, т к put уже подразумевает изменение. Да и {lang} в урле как то странно тоже, так как при put запросах урл - это путь к ресурсу, который будет изменяться, а тут получается, что мы будем менять не ресурс, а сам путь. Ну это как я понимаю смысл rest)) Может быть понимаю неправильно) Но я бы оставил так)

2022-08-25 07:05 UTC, vlbondarenko commented on serverapp/src/WebApi/Controllers/LocalizationController.cs
> +                Expires = DateTime.UtcNow.AddHours(4),
Для языка так не было задумано 🙂 по ошибке добавил

2022-08-25 07:06 UTC, vlbondarenko commented on serverapp/src/WebApi/Controllers/UserController.cs
> +                    Expires = DateTime.UtcNow.AddHours(4)
А тут уже задумано) это чтобы задать время жизни токена в куках)

2022-08-25 07:06 UTC, vlbondarenko commented on serverapp/src/WebApi/Controllers/UserController.cs
> +                    Expires = DateTime.UtcNow.AddHours(4)
При сбросе пароля

2022-08-25 07:07 UTC, vlbondarenko commented on serverapp/src/WebApi/Controllers/UserController.cs
> +            var userId = Request.Cookies["userId"];
Убрал

2022-08-25 07:51 UTC, merged